name: Validate

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions: {}

jobs:
  validate-hacs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: HACS validation (pinned version)
        uses: hacs/action@22.5.0
        with:
          category: integration
          # ignore: ""        # Optionally specify space-separated checks to ignore

      # Optional: Home Assistant hassfest validation
      - name: Hassfest validation
        uses: home-assistant/actions/hassfest@master
